# extends
extends: configs/default.yaml
# general configs
exp_name: wbc_crl
# model configs
model:
  arch: crl
  backbone: resnet34
  n_concepts: 24
  l1: 256
  l2: 256
  use_not: true
  use_skip: true
  temperature: 1
  l2_weight: 5.0e-6
# data configs
data:
  data_dir: /workspace/Datasets/PBC
  dataset: wbcatt
  batch_size: 64
  img_size: 224
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]
  n_concepts: 24
  n_classes: 5
  process_dicts: {"label": {"Basophil": "0", "Eosinophil": "1", "Lymphocyte": "2", "Monocyte": "3", "Neutrophil": "4"}, "binarys": ["big cell size", "round cell shape", "high nuclear cytoplasmic ratio", "densely chromatin density", "clear cytoplasm texture", "yes cytoplasm vacuole", "yes granularity"]}
# opt configs
opt:
  optimizer: adamw
  lr: 5.0e-4
  max_epochs: 300
